export const HOME_PREFIX = 'HOME_'
export const ADVERTS_PREFIX = HOME_PREFIX + 'ADVERTS_'
export const SIDEBAR_TOP_COMPANIES = HOME_PREFIX + 'SIDEBAR_TOP_COMPANIES_'
export const SIDEBAR_MOST_READING = HOME_PREFIX + 'SIDEBAR_MOST_READING_'
