export { default as getSearchResults } from './getSearchResults'
export { default as getComments } from './getComments'
export { default as getNewsPromo } from './getNewsPromo'
export { default as getPost } from './getPost'
export { default as getPosts } from './getPosts'
export { default as getNews } from './getNews'