export const PREFIX = 'SETTINGS_'
export const SET_THEME = PREFIX + 'SET_THEME'
export const SET_HIDDEN_AUTHORS = PREFIX + 'SET_HIDDEN_AUTHORS'
export const SET_HIDDEN_COMPANIES = PREFIX + 'SET_HIDDEN_COMPANIES'
